name: Run basic scripts to check for syntactical correctness 
on:
  push:
    branches-ignore: [ master ]
    tags: 
    - "v1.*"
  pull_request:
    branches: [ master ]

jobs:
  run-xml-linter:
    name: XML linter for UI xml files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Action actors
        run: echo "${{ github.actor }} triggered action by ${{ github.triggering_actor }}"
      - name: install xml linter from utils
        run: sudo apt-get install libxml2-utils
      - name: lint xml files
        run: |
          for file in $(ls *.xml SIDL.xdr); 
          do
            echo Linting $file
            xmllint $file
          done;
